import { antibiotics } from "../data/antibiotics.js";
import { ClinicalLoopEngine, CLINICAL_PHASE } from "../scenarios/ClinicalLoopEngine.js";

export class ClinicalLoopPanel {
  constructor(root, scenarios, onScenarioChange) { this.root = root; this.scenarios = scenarios; this.onScenarioChange = onScenarioChange; this.selected = scenarios[0]; this.engine = new ClinicalLoopEngine(this.selected); this.render(); }
  reset() { this.engine = new ClinicalLoopEngine(this.selected); this.render(); }
  render() { const scenario = this.selected; const engine = this.engine; const phase = engine.phase; const canAdvance = phase !== CLINICAL_PHASE.OUTCOME; const cultureVisible = engine.cultureRevealed; const evaluation = phase === CLINICAL_PHASE.OUTCOME ? engine.evaluate() : null;
    this.root.innerHTML = `<section class="scenario-selector" aria-label="Selección de escenario"><span>FASE 2 · BUCLE CLÍNICO</span><label>Escenario <select id="scenario-select">${this.scenarios.map((item) => `<option value="${item.id}" ${item.id === scenario.id ? "selected" : ""}>${item.title}</option>`).join("")}</select></label></section><section class="clinical-grid"><article class="clinical-card"><p class="eyebrow">${phase}</p><h1>${scenario.title}</h1><p>${scenario.presentation}</p><h2>Resumen clínico</h2><p>${scenario.patient.summary}</p><p><b>Signos vitales:</b> ${scenario.vitalSigns}</p><p><b>Laboratorio:</b> ${scenario.laboratoryData}</p><p class="education-notice">Aviso educativo: este simulador no prescribe ni sustituye guías, antibiogramas locales ni valoración clínica.</p></article><article class="clinical-card decisions"><h2>Decisiones</h2><p>${engine.sourceControlCompleted ? "Control del foco registrado." : scenario.sourceControlOptions[0]?.description ?? "Este caso no requiere una intervención de foco en el flujo."}</p>${scenario.sourceControlOptions.map((option) => `<button data-source-control="${option.id}" ${engine.sourceControlCompleted ? "disabled" : ""}>${option.label}</button>`).join("")}<fieldset><legend>Tratamiento ${cultureVisible ? "dirigido (modificable)" : "empírico"}</legend>${scenario.availableAntibiotics.map((id) => { const item = antibiotics.find((antibiotic) => antibiotic.id === id); return `<label><input type="checkbox" value="${id}" ${engine.therapyIds.includes(id) ? "checked" : ""}> ${item.name}</label>`; }).join("")}</fieldset><button class="primary" id="advance-phase" ${canAdvance ? "" : "disabled"}>${phase === CLINICAL_PHASE.DIRECTED ? "Evaluar resultado" : "Continuar"}</button><button id="restart-scenario">Reiniciar escenario</button></article><article class="clinical-card microbiology"><h2>Microbiología</h2><p>${cultureVisible ? scenario.cultureTimeline.result : "Aún no se revelan organismos ni sensibilidad. Decide con la información clínica inicial."}</p><h2>Objetivos</h2><ul>${scenario.learningObjectives.map((item) => `<li>${item}</li>`).join("")}</ul></article>${evaluation ? `<article class="clinical-card debrief"><p class="eyebrow">DEBRIEF</p><h2>${evaluation.success ? "Resultado educativo: objetivos alcanzados" : "Resultado educativo: revisar decisiones"}</h2><p>${scenario.debriefRules.key}</p><p><b>Cobertura completa:</b> ${evaluation.coverageComplete ? "sí" : "no"} · <b>Control del foco:</b> ${evaluation.sourceControlOk ? "sí" : "no"}</p>${evaluation.feedback.slice(0, 5).map((item) => `<div class="feedback ${item.severity}"><b>Qué:</b> ${item.what}<br><b>Por qué:</b> ${item.why}<br><b>Implicación:</b> ${item.implication}</div>`).join("")}<p class="sources">Fuentes: ${scenario.sourceRefs.join(", ")}</p></article>` : ""}</section>`;
    this.bind(); }
  bind() { this.root.querySelector("#scenario-select").addEventListener("change", (event) => { this.selected = this.scenarios.find((item) => item.id === event.target.value); this.engine = new ClinicalLoopEngine(this.selected); this.onScenarioChange(this.selected); this.render(); }); this.root.querySelectorAll("input[type=checkbox]").forEach((input) => input.addEventListener("change", () => this.engine.selectTherapy([...this.root.querySelectorAll("input[type=checkbox]:checked")].map((item) => item.value)))); this.root.querySelector("[data-source-control]")?.addEventListener("click", () => { this.engine.completeSourceControl(); this.render(); }); this.root.querySelector("#advance-phase").addEventListener("click", () => { this.engine.advance(); this.render(); }); this.root.querySelector("#restart-scenario").addEventListener("click", () => this.reset()); }
}
